# general settings
name: train_synthetic_AutoEncoder_RRDB_LRrecon1
model_type: AEModel
scale: 4
num_gpu: 4   # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: YOUR_HR_DF2K_PATH
    dataroot_lq: YOUR_LR_DF2K_PATH
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: DIV2Kval
    type: PairedImageDataset
    dataroot_gt: /mnt/hdd0/mklee/sr_dataset_fromLDL/DIV2Kmini/HR   # the first 10 images from DIV2Kval (for fast val)
    dataroot_lq: /mnt/hdd0/mklee/sr_dataset_fromLDL/DIV2Kmini/LR
    io_backend:
      type: disk

# network structures
network_g:
  type: AutoEncoder_RRDBNet
  enc_opt:
    placeholder: 0
  dec_opt:
    type: RRDBNet
    num_in_ch: 3
    num_out_ch: 3
    num_feat: 64
    num_block: 23
    num_grow_ch: 32


# path
path:
  pretrain_network_decoder: /mnt/hdd0/mklee/mklee_SR_framework/saved_parameters/official_ESRGAN/ESRGAN_PSNR_SRx4_DF2K_official-150ff491.pth   # official RRDB (ESRGAN PSNR-version) Weight
  param_key_decoder: params_ema
  strict_load_decoder: true
  #
  pretrain_network_g: ~
  param_key_g: ~
  strict_load_g: true
  resume_state: ~




# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [300000]
    gamma: 1

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1
    reduction: mean

  ema_decay: 0.999

  # ---- AE ----
  pixel_at_LR_opt:
    type: L1Loss
    loss_weight: !!float 1
    reduction: mean

  freeze_decoder: 0  # freeze decoder up to this iter (0 = no freeze | 99999999 = always freeze)


# validation settings
val:
  val_freq: !!float 5e3
  val_start_iter: 0
  save_img: true

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true



# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: AESOP_AutoEncoder
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
